### ISSUE TITLE
Heya

### ISSUE THREAD

**Issue by mdjong1** [plaza-in-a-heatwave/Cadesim#30]
Nice stuff on this; you interested in keeping going? And you have a discord or something with the people that actually use it?

**Comment by plaza-in-a-heatwave** [comment]
Hi! yes I'm still interested in seeing this develop but I don't have that much time these days unfortunately. A few people are doing stuff behind the scenes, and there's a now a mighty discord channel where GU hosts about 5 of these servers, but by and large its the same code running.

Whole bucket of suggestions for the future - most of them are performance fixes (reduce lag, prevent client crashes) or features for adding a new lobby system. And the pipe dreams, like making it scale properly... (never gonna happen, most of the graphics are hardcoded :joy:  )

**Comment by mdjong1** [comment]
Sounds great, glad to hear development is still alive in some places. Have a bit of time on my hands myself, so happy to pitch in with stuff where possible
