### ISSUE TITLE
ship doesn't spin in whirlpools

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#82]
When the space it's trying to claim is unoccupied, but something else is also claiming it.

Distinct from the space being occupied (e.g. by rocks in SMH, or by a sunken ship), when it should not spin

**Comment by David52920** [comment]
After fixing some collision code, it seems to spin, but doesn't show up until end of the turn, perhaps a client issue

**Comment by plaza-in-a-heatwave** [comment]
From earlier discussion:
* The faces are changing, but not animating, so must be an animation issue. Unsure whether client or not.
* need to specifically set animation each turn to change face in whirlpool if collision
* Right now there is just a bump subAnimation, may need to add to enum bumpNorthAndTurn, etc
