### ISSUE TITLE
Fanchuan influence diameter display incorrect

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#88]
From discord:

```A: ```The Fanch influence is acting like a Dhow

```B: ```Fanch and dhow have the same influence, do you mean junk?

```A: ```No... - the influence diameter on the fanch in the kade sim shows a larger circle than the dhow but doesnt provide the influence to match. So then is it the influence circle that is wrong?

```B: ```Must be the circle, fanch dhow and cutter all have the same influence

**Comment by David52920** [comment]
Fixed in map editor pull request: influence radius was set to 2 instead of 1. Yppedia shows diamater as 2.
