### ISSUE TITLE
Create automatic build scripts for the client and server

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#91]
Create automatic build scripts for the client and server, and a server regression testing target.
- either using [shadow-jar](https://github.com/johnrengelman/shadow) with gradle, or standard dist target.

Also address some configurability points:
- server won't start if maps directory not present, fatal, but throws cryptic error
- client won't start if user.config doesn't parse, fatal, but throws cryptic error

**Comment by plaza-in-a-heatwave** [comment]
Feature added in branch 91, but paused due to bug with client updater

**Comment by David52920** [comment]
> Feature added in branch 91, but paused due to bug with client updater

Probably need to delete the files (version.txt,digest.txt, digest2.txt)
