### ISSUE TITLE
Clean way needed to stop launched servers

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#94]
Servers that are launched in a multi-room aware configuration currently cannot be stopped gracefully.

Some solutions:
* create a unique working directory per server and store PIDs there to be killed by an external stop script
* have servers react to a STOP file within 10s

## STOP file method
Seems like the most cross-platform way - no need for PIDs.
* each server puts down a unique file indicating it's alive e.g. .CADESIM_INSTANCE_<md5 hash of args>
* servers remove these files when shutting down cleanly
* a shutdown script places a .STOP file in the directory and waits up to n sec for the unique files to disappear

**Comment by mdjong1** [comment]
"clean"

**Comment by plaza-in-a-heatwave** [comment]
> "clean"

Yep, looking at this with fresh eyes I now see its anything but clean 😂 it's still cross platform and simple though which are good things!
