### ISSUE TITLE
Fix getdown.txt parsing

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#95]
Currently we skip a fixed number of lines in ```getdown.txt```, I managed to break this just by adding a comment line. We should parse out the key-value pairs instead.

```
...
sc.readLine();                               # skip a comment (but what if there are more comment lines?)
//get server url from getDown.txt
String cadesimUrl = sc.readLine();
String[] url = cadesimUrl.split("=");
//read version from getDown.txt
String cadeSimVersion = sc.readLine();
...
```

**Comment by David52920** [comment]
Fixed in commit 7837f6ba8e5f5ef637136825fe8255297d4d0274; accidentally wrote incorrect bug in commit description
