### ISSUE TITLE
When making a custom map it doesn't pass across the flags

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#99]
All other elements are carried across

This may be related to MapType.java which loads a map and then removes its flags: ```MapType.java:65```

This may also be related to issue #102 (and PR #106 which addresses it)

**Comment by David52920** [comment]
Correct, MapType.java sets the flags on the server for finalMap but doesn't for the custom map since it load() just returns either finalMap or customMap.

For loop for the custom map should fix it.
